spring.application.name=cine-ticket
server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/cineticket
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
