--
-- PostgreSQL database dump
--



-- Dumped from database version 15.19
-- Dumped by pg_dump version 15.19

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: tb_cinema; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_cinema (
    id bigint NOT NULL,
    cnpj character varying(18) NOT NULL,
    endereco character varying(200) NOT NULL,
    nome character varying(100) NOT NULL
);


ALTER TABLE public.tb_cinema OWNER TO postgres;

--
-- Name: tb_cinema_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_cinema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_cinema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_movie; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_movie (
    id bigint NOT NULL,
    duracao_minutos integer NOT NULL,
    poster_url character varying(500),
    sinopse text,
    titulo character varying(150) NOT NULL,
    tmdb_id character varying(255)
);


ALTER TABLE public.tb_movie OWNER TO postgres;

--
-- Name: tb_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_movie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_role (
    id bigint NOT NULL,
    nome character varying(50) NOT NULL
);


ALTER TABLE public.tb_role OWNER TO postgres;

--
-- Name: tb_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_room (
    id bigint NOT NULL,
    capacidade integer NOT NULL,
    nome character varying(100) NOT NULL,
    cinema_id bigint NOT NULL
);


ALTER TABLE public.tb_room OWNER TO postgres;

--
-- Name: tb_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_seat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_seat (
    id bigint NOT NULL,
    fila character varying(5) NOT NULL,
    numero integer NOT NULL,
    room_id bigint NOT NULL
);


ALTER TABLE public.tb_seat OWNER TO postgres;

--
-- Name: tb_seat_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_seat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_seat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_session (
    id bigint NOT NULL,
    ativo boolean NOT NULL,
    horario_inicio timestamp(6) without time zone NOT NULL,
    valor_base numeric(10,2) NOT NULL,
    movie_id bigint NOT NULL,
    room_id bigint NOT NULL
);


ALTER TABLE public.tb_session OWNER TO postgres;

--
-- Name: tb_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_ticket (
    id bigint NOT NULL,
    status_pagamento character varying(255) NOT NULL,
    ticket_type character varying(255) NOT NULL,
    valor_pago numeric(10,2) NOT NULL,
    seat_id bigint NOT NULL,
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT tb_ticket_status_pagamento_check CHECK (((status_pagamento)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'CANCELLED'::character varying, 'EMERGENCY_CANCELLED'::character varying])::text[]))),
    CONSTRAINT tb_ticket_ticket_type_check CHECK (((ticket_type)::text = ANY ((ARRAY['INTEIRA'::character varying, 'MEIA_ESTUDANTE'::character varying, 'MEIA_IDOSO'::character varying])::text[])))
);


ALTER TABLE public.tb_ticket OWNER TO postgres;

--
-- Name: tb_ticket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_user (
    id bigint NOT NULL,
    email character varying(150) NOT NULL,
    nome character varying(150) NOT NULL,
    senha character varying(255) NOT NULL
);


ALTER TABLE public.tb_user OWNER TO postgres;

--
-- Name: tb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.tb_user_role OWNER TO postgres;

--
-- Name: tb_cinema tb_cinema_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cinema
    ADD CONSTRAINT tb_cinema_pkey PRIMARY KEY (id);


--
-- Name: tb_movie tb_movie_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_movie
    ADD CONSTRAINT tb_movie_pkey PRIMARY KEY (id);


--
-- Name: tb_role tb_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_role
    ADD CONSTRAINT tb_role_pkey PRIMARY KEY (id);


--
-- Name: tb_room tb_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_room
    ADD CONSTRAINT tb_room_pkey PRIMARY KEY (id);


--
-- Name: tb_seat tb_seat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_seat
    ADD CONSTRAINT tb_seat_pkey PRIMARY KEY (id);


--
-- Name: tb_session tb_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_session
    ADD CONSTRAINT tb_session_pkey PRIMARY KEY (id);


--
-- Name: tb_ticket tb_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_ticket
    ADD CONSTRAINT tb_ticket_pkey PRIMARY KEY (id);


--
-- Name: tb_user tb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT tb_user_pkey PRIMARY KEY (id);


--
-- Name: tb_user_role tb_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user_role
    ADD CONSTRAINT tb_user_role_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: tb_user uk4vih17mube9j7cqyjlfbcrk4m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user
    ADD CONSTRAINT uk4vih17mube9j7cqyjlfbcrk4m UNIQUE (email);


--
-- Name: tb_cinema uk54f9unl0nheemk83t3uohhguo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_cinema
    ADD CONSTRAINT uk54f9unl0nheemk83t3uohhguo UNIQUE (cnpj);


--
-- Name: tb_role uk6e9vttep485ay7pmjccprgdus; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_role
    ADD CONSTRAINT uk6e9vttep485ay7pmjccprgdus UNIQUE (nome);


--
-- Name: tb_movie ukbahwejd863a4yxvfeftjxh9w4; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_movie
    ADD CONSTRAINT ukbahwejd863a4yxvfeftjxh9w4 UNIQUE (tmdb_id);


--
-- Name: tb_seat ukng9d91k9ouicuii527lj3hcqs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_seat
    ADD CONSTRAINT ukng9d91k9ouicuii527lj3hcqs UNIQUE (room_id, fila, numero);


--
-- Name: tb_seat fk3el6ykifms6lvro7mb36a0dll; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_seat
    ADD CONSTRAINT fk3el6ykifms6lvro7mb36a0dll FOREIGN KEY (room_id) REFERENCES public.tb_room(id);


--
-- Name: tb_user_role fk7vn3h53d0tqdimm8cp45gc0kl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user_role
    ADD CONSTRAINT fk7vn3h53d0tqdimm8cp45gc0kl FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- Name: tb_user_role fkea2ootw6b6bb0xt3ptl28bymv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_user_role
    ADD CONSTRAINT fkea2ootw6b6bb0xt3ptl28bymv FOREIGN KEY (role_id) REFERENCES public.tb_role(id);


--
-- Name: tb_room fkeaolyui4bohcvb9fn9usyksai; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_room
    ADD CONSTRAINT fkeaolyui4bohcvb9fn9usyksai FOREIGN KEY (cinema_id) REFERENCES public.tb_cinema(id);


--
-- Name: tb_session fkji1fnha5m90w499h3hqraefbp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_session
    ADD CONSTRAINT fkji1fnha5m90w499h3hqraefbp FOREIGN KEY (movie_id) REFERENCES public.tb_movie(id);


--
-- Name: tb_session fklj8kk4odwpjuhaivonhbpctkm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_session
    ADD CONSTRAINT fklj8kk4odwpjuhaivonhbpctkm FOREIGN KEY (room_id) REFERENCES public.tb_room(id);


--
-- Name: tb_ticket fko09can8y8tv5m2y58m3g70wt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_ticket
    ADD CONSTRAINT fko09can8y8tv5m2y58m3g70wt FOREIGN KEY (seat_id) REFERENCES public.tb_seat(id);


--
-- Name: tb_ticket fkoa6dths1eu8gnrlchutafn97o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_ticket
    ADD CONSTRAINT fkoa6dths1eu8gnrlchutafn97o FOREIGN KEY (user_id) REFERENCES public.tb_user(id);


--
-- Name: tb_ticket fkokjv24s7javaqe3xy28ofwmu8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_ticket
    ADD CONSTRAINT fkokjv24s7javaqe3xy28ofwmu8 FOREIGN KEY (session_id) REFERENCES public.tb_session(id);


--
-- PostgreSQL database dump complete
--


