ALTER TABLE tb_cinema ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_cinema ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_movie ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_movie ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_role ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_role ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_room ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_room ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_seat ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_seat ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_session ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_session ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_ticket ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_ticket ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE tb_user ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_user ADD COLUMN updated_at TIMESTAMP;
